# ~/.bashrc - Catppuccin Mocha theme with modern tools

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# ble.sh for fish-like autosuggestions (load early with noattach)
[[ -f /usr/share/blesh/ble.sh ]] && source /usr/share/blesh/ble.sh --noattach

# Set terminal title to "ghostty" (like fish)
PROMPT_COMMAND='echo -ne "\033]0;ghostty\007"'

# History settings
HISTSIZE=10000
HISTFILESIZE=20000
HISTCONTROL=ignoreboth:erasedups
shopt -s histappend

# Use bat for man pages
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"

# FZF Catppuccin Mocha colors
export FZF_DEFAULT_OPTS="
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc
--color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"

# Add ~/.local/bin to PATH
[[ -d ~/.local/bin ]] && [[ ":$PATH:" != *":$HOME/.local/bin:"* ]] && PATH="$HOME/.local/bin:$PATH"

# Aliases - Replace ls with eza
alias ls='eza -al --color=always --group-directories-first --icons'
alias lsz='eza -al --color=always --total-size --group-directories-first --icons'
alias la='eza -a --color=always --group-directories-first --icons'
alias ll='eza -l --color=always --group-directories-first --icons'
alias lt='eza -aT --color=always --group-directories-first --icons'
alias l.='eza -ald --color=always --group-directories-first --icons .*'

# Replace cat with bat
alias cat='bat --style header,snip,changes'

# Modern tool aliases
command -v rg &>/dev/null && alias grep='rg --color=auto'
command -v fd &>/dev/null && alias find='fd'
command -v btop &>/dev/null && alias top='btop'
command -v dust &>/dev/null && alias du='dust'
command -v procs &>/dev/null && alias ps='procs'
command -v duf &>/dev/null && alias df='duf'
command -v lazygit &>/dev/null && alias lg='lazygit'

# Common use
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias big='expac -H M "%m\t%n" | sort -h | nl'
alias fixpacman='sudo rm /var/lib/pacman/db.lck'
alias gitpkg='pacman -Q | grep -i "\-git" | wc -l'
alias grubup='sudo update-grub'
alias hw='hwinfo --short'
alias ip='ip -color'
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias wget='wget -c'
alias rmpkg='sudo pacman -Rdd'
alias tarnow='tar -acf '
alias untar='tar -zxvf '
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias egrep='grep -E --color=auto'
alias fgrep='grep -F --color=auto'

# Mirror management
alias mirror='sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist'
alias mirrora='sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist'
alias mirrord='sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist'
alias mirrors='sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist'

# Help aliases
alias please='sudo'
alias tb='nc termbin.com 9999'
alias helpme='echo "To print basic information about a command use tldr <command>"'
alias pacdiff='sudo -H DIFFPROG=meld pacdiff'

# Journal errors
alias jctl='journalctl -p 3 -xb'

# Recent installed packages
alias rip='expac --timefmt="%Y-%m-%d %T" "%l\t%n %v" | sort | tail -200 | nl'

# Cleanup orphaned packages
cleanup() {
    while pacman -Qdtq &>/dev/null; do
        sudo pacman -R $(pacman -Qdtq)
        [[ $? -eq 1 ]] && break
    done
}

# Backup file
backup() { cp "$1" "$1.bak"; }

# Backup with rsync
sync_backup() { rsync -avhP "$1" "$2"; }

# Copy directory
copy() {
    if [[ $# -eq 2 && -d "$1" ]]; then
        cp -r "${1%/}" "$2"
    else
        cp "$@"
    fi
}

# Extract any archive
extract() {
    if [[ -f "$1" ]]; then
        case "$1" in
            *.tar.bz2) tar xjf "$1" ;;
            *.tar.gz)  tar xzf "$1" ;;
            *.tar.xz)  tar xJf "$1" ;;
            *.bz2)     bunzip2 "$1" ;;
            *.rar)     unrar x "$1" ;;
            *.gz)      gunzip "$1" ;;
            *.tar)     tar xf "$1" ;;
            *.tbz2)    tar xjf "$1" ;;
            *.tgz)     tar xzf "$1" ;;
            *.zip)     unzip "$1" ;;
            *.Z)       uncompress "$1" ;;
            *.7z)      7z x "$1" ;;
            *.xz)      xz -d "$1" ;;
            *)         echo "'$1' cannot be extracted" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# Make directory and cd into it
mkcd() { mkdir -p "$1" && cd "$1"; }

# Quick command reference
quick() {
    echo ""
    echo "Quick Commands"
    echo "-------------------"
    echo ""
    echo "zi (Documents)  # Jump to directory"
    echo "Ctrl+R          # Search history"
    echo "Ctrl+U          # Clear line"
    echo "Ctrl+K          # Delete to end"
    echo "Ctrl+A          # Start of line"
    echo "Ctrl+E          # End of line"
    echo "!!              # Run last command"
    echo "ll              # Detailed file list"
    echo "la              # Show all files"
    echo ""
}

# Bash completion
[[ -f /usr/share/bash-completion/bash_completion ]] && source /usr/share/bash-completion/bash_completion

# FZF keybindings
[[ -f /usr/share/fzf/key-bindings.bash ]] && source /usr/share/fzf/key-bindings.bash
[[ -f /usr/share/fzf/completion.bash ]] && source /usr/share/fzf/completion.bash

# Starship prompt
command -v starship &>/dev/null && eval "$(starship init bash)"

# thefuck - type 'fuck' to fix last command
command -v thefuck &>/dev/null && eval "$(thefuck --alias)"

# Zoxide MUST be last before ble.sh
command -v zoxide &>/dev/null && eval "$(zoxide init bash)"

# Run fastfetch on interactive shell start
[[ -f ~/.config/fastfetch/config.jsonc ]] && command -v fastfetch &>/dev/null && fastfetch --config ~/.config/fastfetch/config.jsonc

# Attach ble.sh (must be last)
# NOTE: For Konsole with kitty images, move fastfetch AFTER ble-attach with 'clear' prefix
[[ ${BLE_VERSION-} ]] && ble-attach
