[Theme]
Current=Catppuccin-Mocha-Mauve
CursorTheme=Catppuccin-Mocha-Mauve-Cursors
Font=Inter,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1

[General]
GreeterEnvironment=QT_SCREEN_SCALE_FACTORS=1.9

[Wayland]
EnableHiDPI=true
